[package]
name = "pallet-did-runtime-api"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "Runtime API for pallet-did"

[dependencies]
codec = { workspace = true }
sp-api = { workspace = true }
sp-std = { workspace = true }

[features]
default = ["std"]
std = [
    "codec/std",
    "sp-api/std",
    "sp-std/std",
]

