[package]
name = "pallet-did-rpc"
version = "1.0.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
description = "RPC interface for pallet-did"

[dependencies]
codec = { workspace = true }
jsonrpsee = { version = "0.16.2", features = ["client-core", "server", "macros"] }
sp-api = { workspace = true }
sp-blockchain = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk.git", branch = "master" }
sp-runtime = { workspace = true }
sp-core = { workspace = true }

[dev-dependencies]

